from app.additions.service import AdditionService
from app.additions.source_filter_runtime import install_addition_source_filters
from app.additions.source_preflight_runtime import install_addition_source_preflight
from app.additions.taxonomy_waf_runtime import install_addition_taxonomy_waf_recovery

install_addition_source_filters()
install_addition_source_preflight()
install_addition_taxonomy_waf_recovery()

__all__=["AdditionService"]
