import {chromium} from "playwright";

const browser=await chromium.launch({headless:true});
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on("console",message=>message.type()==="error"&&errors.push(message.text()));
  page.on("pageerror",error=>errors.push(error.message));
  await page.goto("http://127.0.0.1:8766/",{waitUntil:"networkidle"});
  await page.waitForSelector('[data-state-value="status"]');
  const result=await page.evaluate(async()=>{
    const log=document.querySelector("#collect-logs"),details=document.querySelector("#collect-log-details"),progress=document.querySelector(".head-progress-track");
    const pageRoot=document.querySelector('[data-page="collect"]'),required=["executions-details","queue-details","collect-catalog-quick","collect-context-apply","collect-config-trigger","collect-quick-actions","collect-state-title","collect-log-details"];
    const positions=required.map(id=>document.getElementById(id)?.getBoundingClientRect().top??-1);
    const full=await fetch(`/api/collection/logs_full?run_id=${encodeURIComponent(document.querySelector("[data-run-select]")?.dataset.runSelect||"")}`).then(r=>r.json());
    return {cards:document.querySelectorAll("#collect-cards .state-card").length,tooltips:document.querySelectorAll(".state-section .help-tip").length,details:document.querySelectorAll("#collect-state-details>div").length,stateColumns:getComputedStyle(document.querySelector("#collect-cards")).gridTemplateColumns.split(" ").length,progress:progress?.getAttribute("aria-valuenow"),logHeight:getComputedStyle(log).height,logOverflow:getComputedStyle(log).overflowY,accordionOpen:details.open,copyButton:Boolean(document.querySelector("#collect-copy-log")),fullLogOk:full.ok===true,order:positions.every((value,index)=>value>=0&&(!index||value>=positions[index-1])),executionsClosed:!document.querySelector("#executions-details").open,queueClosed:!document.querySelector("#queue-details").open,quickCatalog:Boolean(document.querySelector("#catalog-quick-load")&&document.querySelector("#catalog-quick-create")&&document.querySelector("#collect-catalog-open")),contextOnly:document.querySelector("#collect-site").closest(".panel").querySelectorAll("#collect-slot").length===0,quickModes:[...document.querySelectorAll("#collect-quick-actions [data-run-mode]")].map(x=>x.dataset.runMode),singlePause:Boolean(document.querySelector("#collect-pause-toggle"))&&!document.querySelector('[data-collection-action="resume"]'),noDuplicates:![...pageRoot.querySelectorAll("h2,summary")].some(x=>/Execuções independentes|Fila encadeada|Slots e contextos|^Categorias$/i.test(x.textContent.trim())),categoriesInConfig:Boolean(document.querySelector("#collect-config-fields #collect-categories"))};
  });
  if(errors.length||result.cards!==12||result.tooltips!==20||result.details!==8||result.stateColumns!==4||result.logHeight!=="400px"||result.logOverflow!=="auto"||result.accordionOpen||!result.copyButton||!result.fullLogOk||!result.order||!result.executionsClosed||!result.queueClosed||!result.quickCatalog||!result.contextOnly||result.quickModes.join(",")!=="full_sync,categories_only,links_only,existing_review"||!result.singlePause||!result.noDuplicates||!result.categoriesInConfig)throw new Error(JSON.stringify({errors,result}));
  const refinement=await page.evaluate(()=>{const contextButtons=[...document.querySelectorAll(".context-operations .actions button")],quick=[...document.querySelectorAll("#collect-quick-actions .quick-action")],mainTabs=document.querySelector(".tabs-main"),storeTabs=document.querySelector(".tabs-store");return {mascot:Boolean(document.querySelector(".mascot-crop img"))&&!document.querySelector(".topbar strong"),processes:Boolean(document.querySelector("#processes-open")),credits:[document.querySelector("#credits-ultrapack")?.textContent,document.querySelector("#credits-plugintheme")?.textContent],storeRight:storeTabs.getBoundingClientRect().right>mainTabs.getBoundingClientRect().right,sticky:getComputedStyle(document.querySelector("#collect-head-progress")).position,contextColumns:getComputedStyle(document.querySelector(".context-panel .form-grid")).gridTemplateColumns.split(" ").length,contextInline:contextButtons.length===2&&Math.abs(contextButtons[0].getBoundingClientRect().top-contextButtons[1].getBoundingClientRect().top)<2,quickUniform:quick.length===6&&quick.every(x=>x.querySelector(".help-tip"))&&Math.max(...quick.map(x=>x.getBoundingClientRect().width))-Math.min(...quick.map(x=>x.getBoundingClientRect().width))<2,startHelp:document.querySelector('[data-run-mode="full_sync"]+ .help-tip')?.dataset.tooltip.includes("site, tipo de item, conta, catálogo")}});if(!refinement.mascot||!refinement.processes||refinement.credits.some(x=>!x)||!refinement.storeRight||refinement.sticky!=="sticky"||refinement.contextColumns!==4||!refinement.contextInline||!refinement.quickUniform||!refinement.startHelp)throw new Error(`Refinamento inválido: ${JSON.stringify(refinement)}`);
  await page.click("#processes-open");if(!await page.locator("#executions-details").evaluate(node=>node.open))throw new Error("Processos não abriu Execuções Simultâneas");await page.locator("#executions-details summary").click();
  await page.evaluate(()=>scrollTo(0,800));await page.waitForTimeout(100);const stickyBefore=await page.locator("#collect-head-progress").evaluate(node=>node.getBoundingClientRect().top);await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.waitForTimeout(100);const stickyAfter=await page.locator("#collect-head-progress").evaluate(node=>node.getBoundingClientRect().top);if(Math.abs(stickyAfter-stickyBefore)>2)throw new Error(`Barra sticky deslocou: ${stickyBefore} -> ${stickyAfter}`);await page.locator('[data-tab="compare"]').click();if(await page.locator("#collect-head-progress").isVisible())throw new Error("Barra de coleta visível fora da aba Coletar");await page.locator('[data-tab="collect"]').click();await page.evaluate(()=>scrollTo(0,0));
  await page.locator("#executions-details summary").click();if(!await page.locator("#collect-runs").isVisible())throw new Error("Execuções Simultâneas não abriu");await page.locator("#executions-details summary").click();
  await page.locator("#queue-details summary").click();if(!await page.locator("#queue-rules").isVisible())throw new Error("Fila não abriu");await page.locator("#queue-details summary").click();
  const modes=[];await page.route("**/api/collection/start",async route=>{modes.push(route.request().postDataJSON().mode);await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({ok:true,message:"E2E",state:{status:"Pronto",running:false,paused:false}})})});
  for(const mode of ["full_sync","categories_only","links_only","existing_review"]){const button=page.locator(`#collect-quick-actions [data-run-mode="${mode}"]`);await button.waitFor({state:"visible"});await button.click();await page.waitForFunction(()=>[...document.querySelectorAll("#collect-quick-actions [data-run-mode]")].every(button=>!button.disabled))}if(modes.join(",")!=="full_sync,categories_only,links_only,existing_review")throw new Error(`Modos rápidos incorretos: ${modes}`);
  await page.click("#collect-context-apply");await page.click("#collect-context-reload");await page.click("#catalog-quick-load");
  await page.click("#catalog-quick-clear");if(!await page.locator('#collect-action-modal[open]:has-text("Limpar catálogo")').count())throw new Error("Limpar rápido não confirmou");await page.keyboard.press("Escape");
  await page.click("#collect-catalog-open");await page.waitForSelector("#collect-catalog-modal[open]");await page.keyboard.press("Escape");
  await page.click("#collect-config-open");await page.waitForSelector("#collect-config-modal[open]");await page.selectOption("#collect-scope","selected");if(!await page.locator("#config-categories").isVisible())throw new Error("Categorias não apareceram para escopo selecionado");await page.keyboard.press("Escape");
  await page.setViewportSize({width:375,height:800});const mobile=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,stateColumns:getComputedStyle(document.querySelector("#collect-cards")).gridTemplateColumns.split(" ").length}));if(mobile.overflow||mobile.stateColumns!==1)throw new Error(`Layout móvel inválido: ${JSON.stringify(mobile)}`);
  console.log(JSON.stringify({ok:true,consoleErrors:0,quickInteractions:true,...result}));
}finally{await browser.close()}
