import{chromium}from"playwright";
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on("console",m=>m.type()==="error"&&errors.push(m.text()));page.on("pageerror",e=>errors.push(e.message));
 await page.goto("http://127.0.0.1:8766/",{waitUntil:"networkidle"});await page.click('[data-tab="compare"]');await page.waitForSelector('#compare-rows tr:not(:has-text("Nenhuma comparação"))');
 const structure=await page.evaluate(()=>{const root=document.querySelector('[data-page="compare"]'),blocks=[...root.children].filter(x=>x.matches('.panel'));return{blocks:blocks.map(x=>x.id),headings:blocks.map(x=>x.querySelector('h2,summary')?.textContent.trim()),headerRun:root.querySelector('.page-head [data-comparison-run]'),columns:[...root.querySelectorAll('.comparison-table th')].map(x=>x.textContent.trim()),filters:["comparison-status","comparison-decision","comparison-query","comparison-confidence","comparison-score-min","comparison-score-max"].every(id=>document.getElementById(id)),selection:["comparison-select-page","comparison-select-all","comparison-clear-selection","comparison-selected-count","comparison-bulk-apply","comparison-bulk-decision"].every(id=>document.getElementById(id)),pagination:["comparison-page-size","comparison-prev","comparison-page-input","comparison-total-pages","comparison-next"].every(id=>document.getElementById(id)),catalogs:["comparison-manage-catalogs","comparison-update-catalog","comparison-source","comparison-site","comparison-status-band","comparison-refresh-list"].every(id=>document.getElementById(id)),logClosed:!document.querySelector('#comparison-log-details').open}});
 const wanted=["Situação","Produtos","Versões","Candidato principal","Correspondência","Decisão","Recomendação"];
 if(errors.length||structure.blocks.join(",")!=="comparison-setup,comparison-results,comparison-log-details"||structure.headings.join(",")!=="Comparação de catálogos,Resultado,Log da comparação"||structure.headerRun||structure.columns.join(",")!==wanted.join(",")||!structure.filters||!structure.selection||!structure.pagination||!structure.catalogs||!structure.logClosed)throw new Error(JSON.stringify({errors,structure}));
 await page.click("#comparison-manage-catalogs");await page.waitForSelector("#comparison-catalog-modal[open]");await page.keyboard.press("Escape");
 await page.route("**/api/catalogs/generate",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({ok:true,status:"running",progress:0,logs:["E2E"]})}));await page.route("**/api/catalogs/generation",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({ok:true,status:"error",progress:0,logs:["Falha E2E controlada"]})}));await page.click("#comparison-update-catalog");await page.waitForFunction(()=>document.querySelector("#comparison-status-band").textContent.includes("Falha E2E controlada"));
 await page.selectOption("#comparison-page-size","5");await page.waitForFunction(()=>document.querySelectorAll("#compare-rows tr").length===5);await page.click("#comparison-select-page");if(!await page.locator("#comparison-selected-count").textContent().then(x=>x.startsWith("5 ")))throw new Error("Seleção da página incorreta");await page.click("#comparison-select-page");if(!await page.locator("#comparison-selected-count").textContent().then(x=>x.startsWith("0 ")))throw new Error("Desmarcação da página incorreta");await page.click("#comparison-select-all");if(await page.locator("#comparison-selected-count").textContent()==="0 selecionados")throw new Error("Seleção filtrada não aplicada");await page.click("#comparison-clear-selection");if(!(await page.locator("#comparison-bulk-apply").isDisabled()))throw new Error("Aplicação em massa deveria estar desabilitada");
 await page.fill("#comparison-score-min","90");await page.fill("#comparison-score-max","20");await page.locator("#comparison-score-max").blur();await page.waitForFunction(()=>document.querySelector("#comparison-filter-error").textContent.includes("mínima"));await page.fill("#comparison-score-min","");await page.fill("#comparison-score-max","");await page.locator("#comparison-score-max").blur();
 const pages=+await page.locator("#comparison-total-pages").textContent();if(pages>1){await page.fill("#comparison-page-input","2");await page.keyboard.press("Enter");await page.waitForFunction(()=>document.querySelector("#comparison-page-input").value==="2")}
 await page.click("#comparison-log-details summary");if(!await page.locator("#comparison-log").isVisible())throw new Error("Log não abriu");
 await page.setViewportSize({width:375,height:800});const mobile=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,filterColumns:getComputedStyle(document.querySelector('.comparison-filter-grid')).gridTemplateColumns.split(' ').length}));if(mobile.overflow||mobile.filterColumns!==1)throw new Error(JSON.stringify(mobile));
 if(errors.length)throw new Error(JSON.stringify(errors));console.log(JSON.stringify({ok:true,blocks:3,columns:wanted.length,modal:true,generationFeedback:true,filters:true,selection:true,pagination:true,log:true,consoleErrors:0}));
}finally{await browser.close()}
