import {spawn} from "node:child_process";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {chromium} from "playwright";

const port="8776",fixture=mkdtempSync(join(tmpdir(),"crapscraper-credits-e2e-")),cwd=new URL("..",import.meta.url).pathname.replace(/^\/(.:)/,"$1");
const server=spawn("python",["main.py"],{cwd,env:{...process.env,SCRAPER_PORT:port,SCRAPER_DATA_DIR:fixture,SCRAPER_UPDATE_IMPORT_LEGACY:"0",SCRAPER_ADDITION_IMPORT_LEGACY:"0",SCRAPER_STORE_E2E_FIXTURES:"1"},stdio:"ignore"});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function ready(){for(let i=0;i<40;i++){try{if((await fetch(`http://127.0.0.1:${port}/api/health`)).ok)return}catch{}await sleep(250)}throw new Error("Servidor não iniciou")}
let browser;
try{
  await ready();browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[],requests=[];let forced=0,failNext=false;
  page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});page.on("pageerror",error=>errors.push(error.message));
  await page.route('**/api/credits?*',async route=>{const url=new URL(route.request().url()),site=url.searchParams.get("site_key"),account=url.searchParams.get("account_key")||"default",refresh=url.searchParams.get("refresh")==="1";requests.push({site,account,refresh});if(refresh){forced++;await sleep(180)}const amount=site==="plugintheme"?12:account==="account-b"?22:37,payload=failNext&&refresh?{ok:false,site_key:site,account_key:account,credits:amount,remaining:amount,status:"expired",stale:true,message:"Sessão expirada.",last_confirmed_at:"2026-08-31T03:42:00+00:00",failed_at:"2026-08-31T04:00:00+00:00",logs:["Sessão expirada."]}:{ok:true,site_key:site,account_key:account,credits:amount,remaining:amount,status:"success",last_confirmed_at:"2026-08-31T03:42:00+00:00",logs:[`Saldo localizado: ${amount}.`]};failNext=false;await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(payload)})});
  await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:"networkidle"});await page.waitForFunction(()=>document.querySelector("#credits-ultrapack").textContent.includes("37")&&document.querySelector("#credits-plugintheme").textContent.includes("12"));
  await page.evaluate(()=>{const button=document.querySelector('[data-credit-refresh="ultrapackv2"]');for(let i=0;i<5;i++)button.click()});await sleep(30);const loading=await page.evaluate(()=>({disabled:document.querySelector('[data-credit-refresh="ultrapackv2"]').disabled,spinning:document.querySelector('[data-credit-refresh="ultrapackv2"]').classList.contains("is-loading"),status:document.querySelector("#credits-ultrapack-status").textContent,minHeight:parseFloat(getComputedStyle(document.querySelector("#credits-ultrapack-status")).minHeight)}));if(!loading.disabled||!loading.spinning||!loading.status.includes("Consultando")||loading.minHeight<20)throw new Error(`Estado de loading inválido: ${JSON.stringify(loading)}`);await page.waitForFunction(()=>!document.querySelector('[data-credit-refresh="ultrapackv2"]').disabled);if(forced!==1)throw new Error(`Cinco cliques criaram ${forced} consultas`);
  await page.evaluate(()=>document.dispatchEvent(new CustomEvent("collection:context",{detail:{context:{site_key:"ultrapackv2",account_key:"account-b"}}})));await page.waitForFunction(()=>document.querySelector("#credits-ultrapack").textContent.includes("22"));if(requests.at(-1).account!=="account-b"||!(await page.locator("#credits-plugintheme").innerText()).includes("12"))throw new Error("Troca de conta/fonte vazou saldo");
  failNext=true;await page.locator('[data-credit-refresh="ultrapackv2"]').click();await page.waitForFunction(()=>!document.querySelector('[data-credit-refresh="ultrapackv2"]').disabled);const stale=await page.evaluate(()=>({value:document.querySelector("#credits-ultrapack").textContent,status:document.querySelector("#credits-ultrapack-status").textContent}));if(!stale.value.includes("22")||!stale.status.includes("Última confirmação")||!stale.status.includes("Sessão expirada"))throw new Error(`Último saldo não foi preservado: ${JSON.stringify(stale)}`);
  await page.setViewportSize({width:390,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error("Créditos causaram overflow horizontal");
  if(errors.length)throw new Error(errors.join(" | "));console.log(JSON.stringify({ok:true,manualRefresh:true,loading:true,coalesced:true,accountIsolation:true,stale:true,responsive:true,forcedRequests:forced}));
}finally{if(browser)await browser.close();server.kill();await Promise.race([new Promise(resolve=>server.once("exit",resolve)),sleep(5000)]);rmSync(fixture,{recursive:true,force:true,maxRetries:5,retryDelay:200})}
