import {spawn} from "node:child_process";
import {mkdtempSync,rmSync,mkdirSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {chromium} from "playwright";
const port="8770",fixture=mkdtempSync(join(tmpdir(),"crapscraper-update-e2e-")),cwd=new URL("..",import.meta.url).pathname.replace(/^\/(.:)/,"$1");
mkdirSync(join(fixture,"slots/default/ultrapackv2/plugin/coproducaolancamentos"),{recursive:true});
mkdirSync(join(fixture,"imports"),{recursive:true});
writeFileSync(join(fixture,"slots/default/ultrapackv2/plugin/coproducaolancamentos/catalog.csv"),
  "nome_produto,versao_produto,pagina_oficial,categoria_nome,link_produto\n"+
  Array.from({length:16},(_,i)=>`E2E Plugin ${i+1},2.0,https://vendor.test/${i+1},Plugins,https://ultrapackv2.example/product/${i+1}`).join("\n"));
writeFileSync(join(fixture,"imports/plugintema-products.csv"),
  "ID,Nome,Tipo,Metadado: pt_versao,Metadado: site_oficial,URL,Categorias\n"+
  Array.from({length:15},(_,i)=>`${101+i},E2E Plugin ${i+1},variable,1.0,https://vendor.test/${i+1},https://shop.test/${i+1},Plugins`).join("\n"));
const cleanEnv=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith("SCRAPER_")));
const server=spawn(process.env.PYTHON||"python",["tests/e2e_server.py"],{cwd,env:{...cleanEnv,SCRAPER_PORT:port,SCRAPER_DATA_DIR:fixture,SCRAPER_COMPARISON_DECISIONS_DB_PATH:join(fixture,"comparison.sqlite3"),SCRAPER_UPDATE_IMPORT_LEGACY:"0",SCRAPER_ADDITION_IMPORT_LEGACY:"0",SCRAPER_ADDITION_E2E_FIXTURES:"1",SCRAPER_STORE_E2E_FIXTURES:"1",SCRAPER_STORE_WRITE_ENABLED:"0",SCRAPER_WORDPRESS_MANUAL_POLLING_ENABLED:"0"},stdio:"ignore"});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ready(){for(let i=0;i<40;i++){try{const r=await fetch(`http://127.0.0.1:${port}/api/health`);if(r.ok)return}catch{}await sleep(250)}throw new Error("Servidor não iniciou")}
let browser;
try{
  await ready();browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));page.on("response",r=>{if(r.status()===404)errors.push(`404 ${r.url()}`)});
  await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:"networkidle"});
  await page.click('[data-tab="collect"]');await page.waitForFunction(()=>document.querySelectorAll('#collect-site option').length>=2);if(await page.locator('#collect-site option[value="ultrapackv2"]').count()!==1||await page.locator('#collect-site option[value="plugintheme"]').count()!==1)throw new Error("Registries reais ausentes");
  if(await page.locator("#collect-log-details").count()!==1)throw new Error("Accordion de coleta não é único");
  const runFixture=await page.evaluate(async()=>{const primary=await fetch('/api/collection/context').then(r=>r.json()),a=primary.runs[0],target=primary.context.site_key==='plugintheme'?{site_key:'ultrapackv2',item_type_key:'plugin',account_key:'coproducaolancamentos',slot_name:primary.context.slot_name}:{site_key:'plugintheme',item_type_key:'plugin_theme',account_key:'coproducaolancamentos',slot_name:primary.context.slot_name},b=await fetch('/api/collection/runs/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(target)}).then(r=>r.json());return {a:a.run_id,aContext:a.context,b:b.run_id,bContext:target}});
  await page.reload({waitUntil:"networkidle"});await page.click('[data-tab="collect"]');await page.locator("details:has(#collect-runs) > summary").click();await page.waitForSelector(`[data-run-select="${runFixture.b}"]`);
  const visibleContext=()=>page.evaluate(()=>({site_key:document.querySelector('#collect-site').value,item_type_key:document.querySelector('#collect-type').value,account_key:document.querySelector('#collect-account').value,slot_name:document.querySelector('#collect-slot').value,selected:document.querySelector('#collect-runs .selected [data-run-select]')?.dataset.runSelect}));
  for(const run of [runFixture.b,runFixture.a,runFixture.b,runFixture.a]){await page.locator(`[data-run-select="${run}"]`).click();await page.waitForFunction(id=>document.querySelector('#collect-runs .selected [data-run-select]')?.dataset.runSelect===id,run);const got=await visibleContext(),expected=run===runFixture.a?runFixture.aContext:runFixture.bContext;if(got.site_key!==expected.site_key||got.item_type_key!==expected.item_type_key||got.account_key!==expected.account_key||got.slot_name!==expected.slot_name)throw new Error(`Contexto visual divergente para ${run}: ${JSON.stringify({got,expected,runFixture})}`)}
  const aBefore=(await page.evaluate(id=>fetch(`/api/collection/state?run_id=${id}`).then(r=>r.json()),runFixture.a)).state;await page.locator(`[data-run-select="${runFixture.b}"]`).click();let queuePayload=null,controlPayloads=[],collectionRunning=false,collectionPaused=false;
  await page.route('**/api/collection/state?*',async route=>{
    const response=await route.fetch(),data=await response.json();
    if(new URL(route.request().url()).searchParams.get('run_id')===runFixture.b){
      data.state={...data.state,running:collectionRunning,paused:collectionPaused,status:collectionRunning?'Rodando':'Pronto'};
    }
    await route.fulfill({response,json:data});
  });await page.route('**/api/collection/queue',async route=>{queuePayload=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,queue_rules:queuePayload.rules})})});for(const action of ['start','pause','stop'])await page.route(`**/api/collection/${action}`,async route=>{controlPayloads.push({action,body:route.request().postDataJSON()});if(action==='start'){collectionRunning=true;collectionPaused=false}else if(action==='pause'){collectionPaused=true}else{collectionRunning=false;collectionPaused=false}await route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'})});await page.locator('details:has(#queue-add) > summary').click();await page.locator('#queue-add').click();for(const mode of ['full_sync','categories_only','links_only','existing_review']){await page.locator(`[data-collection-action="start"][data-run-mode="${mode}"]`).click();for(const action of ['pause','stop'])await page.locator(`[data-collection-action="${action}"]`).click();}if(controlPayloads.length!==12)throw new Error('Collection controls did not complete all four lifecycles');if(JSON.stringify(controlPayloads.filter(x=>x.action==='start').map(x=>x.body.mode))!==JSON.stringify(['full_sync','categories_only','links_only','existing_review']))throw new Error('Modos de coleta divergentes: '+JSON.stringify(controlPayloads));if(queuePayload.rules.at(-1).source.site_key!==runFixture.bContext.site_key||controlPayloads.some(x=>x.body.run_id!==runFixture.b))throw new Error(`Ações não usaram run B: ${JSON.stringify({queuePayload,controlPayloads})}`);const aAfter=(await page.evaluate(id=>fetch(`/api/collection/state?run_id=${id}`).then(r=>r.json()),runFixture.a)).state;if(aAfter.status!==aBefore.status||JSON.stringify(aAfter.logs)!==JSON.stringify(aBefore.logs))throw new Error("Run A foi alterada por controles da run B");
  page.once('dialog',dialog=>dialog.accept());await page.locator(`[data-run-remove="${runFixture.b}"]`).click();await page.waitForFunction(id=>!document.querySelector(`[data-run-select="${id}"]`),runFixture.b);const afterRemove=await visibleContext();if(afterRemove.site_key!==runFixture.aContext.site_key)throw new Error("Remover run B alterou o contexto primário");
  await page.click('#collect-catalog-open');await page.waitForSelector('#collect-catalog-modal[open]');
  await page.locator('#catalog-context-search').fill('ultrapackv2');
  await page.locator('#catalog-context-rows [data-context-preview="catalog"]:not([disabled])').first().click();
  await page.waitForSelector('#catalog-preview-content tbody tr');
  if(!(await page.locator('#catalog-preview-page').innerText()).includes('16 item'))throw new Error('Pr?via n?o preservou os 16 produtos do fixture');
  const downloadPending=page.waitForEvent('download');await page.locator('#catalog-context-rows [data-context-download]:not([disabled])').first().click();
  const download=await downloadPending;if(await download.failure())throw new Error('Download CSV falhou');
  await page.locator('#collect-catalog-modal [data-dialog-close]').click();
  await page.click('[data-tab="compare"]');await page.click('#comparison-update-catalog');await page.waitForSelector('#catalog-generation-modal[open]');
  await page.locator('input[name="catalog-kind"][value="plugin"]').check();await page.locator('#catalog-generation-submit').click();
  await page.waitForFunction(()=>document.querySelector('#catalog-generation-status-band').classList.contains('success'));
  const generation=await page.evaluate(()=>fetch('/api/catalogs/generation').then(r=>r.json()));
  if(generation.status!=='completed'||generation.result.items_count!==15)throw new Error('Gera??o incompleta: '+JSON.stringify(generation));
  await page.locator('#catalog-generation-cancel').click();
  await page.click('[data-tab="compare"]');await page.waitForSelector("#compare-rows tr",{timeout:240000});const rows=await page.locator("#compare-rows tr").count();if(!rows)throw new Error("Comparação sem resultados");
  await page.locator('#comparison-score-min').fill('0');await page.locator('#comparison-score-max').fill('100');await page.locator('#comparison-score-max').press('Tab');await sleep(500);await page.locator('#comparison-select-page').click();if(!(await page.locator('#comparison-selected-count').innerText()).includes(String(await page.locator('#compare-rows tr').count())))throw new Error("Seleção da página divergente");await page.locator('#comparison-clear-selection').click();await page.locator('#comparison-select-all').click();if(!(await page.locator('#comparison-selected-count').innerText()).includes('no resultado filtrado'))throw new Error("Seleção global filtrada ausente");await page.locator('#comparison-clear-selection').click();await page.locator('#comparison-select-page').click();await page.locator('#comparison-bulk-decision').selectOption('review_later');await page.locator('#comparison-bulk-apply').click();await page.waitForFunction(()=>document.querySelector('#comparison-selected-count').textContent.startsWith('0 '),null,{timeout:60000});await page.locator('#compare-rows [data-reset-decision]').first().click();await page.waitForFunction(()=>document.querySelector('#comparison-log').textContent.includes('Fonte:'),null,{timeout:60000});
  await page.locator("#comparison-query").fill("plugin");await sleep(700);if(await page.locator("#comparison-query").inputValue()!=="plugin")throw new Error("Busca da comparação foi perdida");
  await page.locator("#compare-rows [data-link]").first().click();await page.waitForSelector("#relationship-modal[open]");await page.keyboard.press("Escape");if(await page.locator("#relationship-modal[open]").count())throw new Error("Escape não fechou modal");
  await page.click('[data-tab="update"]');await page.waitForSelector("#update-cards .card");
  if(await page.locator("#update-cards .card").count()!==6)throw new Error("Atualizar deve exibir Total, Preparados, Na fila, Em andamento, Concluídos e Erros");
  if((await page.locator("#update-cards").innerText()).includes("Aguardando"))throw new Error("Card Aguardando reapareceu");
  const counts=await page.locator("#update-cards .card strong").allTextContents();if(Number(counts[0])!==counts.slice(1).reduce((a,v)=>a+Number(v),0))throw new Error("Total dos cards incoerente");
  await page.locator('#update-cards [data-update-group="prepared"]').click();await sleep(350);if(await page.locator("#update-list article[data-job-id]").count()!==Number(counts[1]))throw new Error("Filtro Preparados diverge do contador");
  await page.locator('#update-cards [data-update-group="error"]').click();await sleep(350);if(await page.locator("#update-list article[data-job-id]").count()!==Number(counts[5]))throw new Error("Filtro Erros diverge do contador");
  await page.locator("#update-query").fill("persistir busca");await page.evaluate(()=>{const d=document.querySelector("#update-log-details");d.open=true;window.__updateDetails=d});await sleep(26000);
  const stable=await page.evaluate(()=>({same:window.__updateDetails===document.querySelector("#update-log-details"),open:document.querySelector("#update-log-details").open,query:document.querySelector("#update-query").value,page:document.querySelector("#update-page-input").value}));if(!stable.same||!stable.open||stable.query!=="persistir busca"||stable.page!=="1")throw new Error("Polling alterou DOM/estado: "+JSON.stringify(stable));
  await page.evaluate(()=>document.querySelector("#update-log-details").open=false);await sleep(2600);if(await page.locator("#update-log-details").evaluate(d=>d.open))throw new Error("Polling reabriu log fechado");
  await page.click('[data-tab="add"]');await page.waitForSelector("#add-cards .card");if(await page.locator("#add-cards").count()!==1||await page.locator("#add-cards .card").count()!==5)throw new Error("Adicionar não possui um único conjunto de cinco cards");
  await page.locator("#add-page-size").selectOption("100");
  const addCounts=await page.locator("#add-cards .card strong").allTextContents();if(Number(addCounts[0])!==addCounts.slice(1).reduce((a,v)=>a+Number(v),0))throw new Error("Total de Adicionar incoerente");
  await page.locator('#add-cards [data-add-group="prepared"]').click();await sleep(350);if(await page.locator("#add-list tr[data-add-job]").count()!==Number(addCounts[1]))throw new Error("Preparados de Adicionar divergem do card");
  await page.locator('#add-cards [data-add-group="error"]').click();await sleep(350);if(await page.locator("#add-list tr[data-add-job]").count()!==Number(addCounts[4]))throw new Error("Erros de Adicionar divergem do card");
  await page.locator("#add-list [data-add-select]").first().click();await page.waitForFunction(()=>document.querySelector("#add-details").textContent.includes("PluginTheme"));
  await page.keyboard.press("Escape");await page.locator('#add-cards [data-add-group=""]').click();await page.locator("#add-page-size").selectOption("10");await sleep(500);await page.locator("#add-next").click();await sleep(4000);if(!(await page.locator("#add-page").innerText()).includes("Página 2")||await page.locator("#add-page-size").inputValue()!=="10")throw new Error("Polling não preservou página 2/page size em Adicionar");await page.locator("#add-query").fill("e2e-add");await sleep(350);
  await page.evaluate(()=>{const details=document.querySelector("#add-log-details");details.open=true;window.__addDetails=details});await sleep(26000);
  const addStable=await page.evaluate(()=>({same:window.__addDetails===document.querySelector("#add-log-details"),open:document.querySelector("#add-log-details").open,query:document.querySelector("#add-query").value,group:document.querySelector("#add-group").value,pageSize:document.querySelector("#add-page-size").value,page:document.querySelector("#add-page").textContent}));if(!addStable.same||!addStable.open||addStable.query!=="e2e-add"||addStable.group!==""||addStable.pageSize!=="10"||!addStable.page.includes("Página 1"))throw new Error("Polling de Adicionar alterou DOM/estado: "+JSON.stringify(addStable));
  await page.evaluate(()=>document.querySelector("#add-log-details").open=false);await sleep(2600);if(await page.locator("#add-log-details").evaluate(d=>d.open))throw new Error("Polling reabriu log de Adicionar");
  console.log('E2E: collection, catalogs, comparison, update and addition polling passed');
  await page.click('[data-tab="store"]');await page.waitForSelector('#store-quality tr[data-store-select]');
  if(await page.locator('.store-pricing-accordion').count()!==3)throw new Error("Loja deve apresentar três grupos de preços");
  await page.locator('#store-monitor-toggle').click();await page.waitForFunction(()=>document.querySelector('#store-monitor-toggle').getAttribute('aria-checked')==='true');
  await page.locator('#store-quality tr[data-store-select]').first().click();await page.waitForFunction(()=>document.querySelector('#store-details').textContent.includes('WooCommerce'));
  await page.evaluate(()=>{window.__storeDetails=document.querySelector('#store-details')});await sleep(2600);
  if(!await page.evaluate(()=>window.__storeDetails===document.querySelector('#store-details')))throw new Error("Polling substituiu detalhes da Loja");
  console.log('E2E: store passed');
  if(await page.locator("#manual-sync-modal").count()!==1)throw new Error("Modal de sincronização não é único");await page.locator("#manual-sync-open").click();await page.waitForSelector("#manual-sync-modal[open]");await page.waitForSelector("#manual-sync-modal[open]");await page.evaluate(()=>window.__manualSyncDialog=document.querySelector("#manual-sync-modal"));await page.keyboard.press("Escape");if(await page.locator("#manual-sync-modal[open]").count())throw new Error("Escape não fechou sincronização");await page.locator("#manual-sync-open").click();await page.waitForSelector("#manual-sync-modal[open]");await page.evaluate(()=>document.querySelector("#manual-sync-modal").dispatchEvent(new MouseEvent("click",{bubbles:true})));if(await page.locator("#manual-sync-modal[open]").count())throw new Error("Backdrop não fechou sincronização");
  console.log('E2E: manual sync selection');
  await page.locator("#manual-sync-open").click();await page.waitForSelector("#manual-sync-modal[open]");await page.locator("#manual-sync-site-search").click();await page.waitForSelector('#manual-sync-site-results [data-sync-select="site"]',{timeout:240000});await page.locator('#manual-sync-site-results [data-sync-select="site"]').first().click();await page.locator("#manual-sync-source-search").click();await page.waitForSelector('#manual-sync-source-results [data-sync-select="source"]',{timeout:240000});await page.locator('#manual-sync-source-results [data-sync-select="source"]').first().click();await sleep(4000);const syncSelectionStable=await page.evaluate(()=>({same:window.__manualSyncDialog===document.querySelector("#manual-sync-modal"),site:document.querySelectorAll('#manual-sync-site-results [data-sync-select].selected').length,source:document.querySelectorAll('#manual-sync-source-results [data-sync-select].selected').length}));if(!syncSelectionStable.same||syncSelectionStable.site!==1||syncSelectionStable.source!==1)throw new Error("Polling alterou modal/seleção: "+JSON.stringify(syncSelectionStable));await page.locator("#manual-sync-review").click();await page.waitForFunction(()=>!document.querySelector("#manual-sync-review-panel").hidden);if(!(await page.locator("#manual-sync-review-content").innerText()).includes("Atualizar produto existente"))throw new Error("Sincronização não classificou update");await page.locator("#manual-sync-execute").click();await page.waitForFunction(()=>document.querySelector("#manual-sync-result").textContent.includes("success"));const updateJob=(await page.locator("#manual-sync-result p").first().innerText()).split(" · ")[1];await page.locator("#manual-sync-execute").click();await sleep(300);const updateStatus=await page.evaluate(job=>fetch(`/api/sync/status?job_id=${encodeURIComponent(job)}`).then(r=>r.json()),updateJob);if(updateStatus.operation!=="update"||updateStatus.execution_count!==1)throw new Error("UpdateExecutor fake não recebeu exatamente um job: "+JSON.stringify(updateStatus));await page.locator("#manual-sync-close").click();
  await page.locator("#manual-sync-open").click();await page.waitForSelector("#manual-sync-modal[open]");await page.locator("#manual-sync-operation").selectOption("addition");if(!(await page.locator("#manual-sync-site-section").evaluate(x=>x.hidden)))throw new Error("Fluxo novo manteve produto existente");await page.locator("#manual-sync-source-search").click();await page.waitForSelector('#manual-sync-source-results [data-sync-select="source"]');await page.locator('#manual-sync-source-results [data-sync-select="source"]').first().click();await page.locator("#manual-sync-review").click();await page.waitForFunction(()=>!document.querySelector("#manual-sync-review-panel").hidden);if(!(await page.locator("#manual-sync-review-content").innerText()).includes("Adicionar novo produto"))throw new Error("Sincronização não classificou addition");await page.locator("#manual-sync-execute").click();await page.waitForFunction(()=>document.querySelector("#manual-sync-result").textContent.includes("success"));const additionJob=(await page.locator("#manual-sync-result p").first().innerText()).split(" · ")[1];const additionStatus=await page.evaluate(job=>fetch(`/api/sync/status?job_id=${encodeURIComponent(job)}`).then(r=>r.json()),additionJob);if(additionStatus.operation!=="addition"||additionStatus.execution_count!==1)throw new Error("AdditionExecutor fake não recebeu exatamente um job: "+JSON.stringify(additionStatus));await page.locator("#manual-sync-close").click();
  await page.setViewportSize({width:390,height:844});const overflow=await page.evaluate(()=>({page:document.documentElement.scrollWidth>innerWidth,elements:[...document.querySelectorAll("body *")].filter(x=>x.getBoundingClientRect().right>innerWidth+1&&!x.closest(".table-wrap,.tabs")).slice(0,8).map(x=>({tag:x.tagName,id:x.id,class:x.className,right:Math.round(x.getBoundingClientRect().right)}))}));if(overflow.page)throw new Error("Overflow horizontal mobile: "+JSON.stringify(overflow.elements));
  if(errors.length)throw new Error(errors.join(" | "));console.log(JSON.stringify({ok:true,collection:true,comparison:true,updates:true,additions:true,store:true,directSync:true,updateDetailsStable:true,addDetailsStable:true,storeDetailsStable:true,manualSyncDialogStable:true,rows,mobile:true,consoleErrors:0,notFound:0}));
}finally{if(browser)await browser.close();server.kill();await Promise.race([new Promise(resolve=>server.once("exit",resolve)),sleep(5000)]);rmSync(fixture,{recursive:true,force:true,maxRetries:5,retryDelay:200})}
