import{chromium}from"playwright";
const browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on("console",m=>m.type()==="error"&&errors.push(m.text()));page.on("pageerror",e=>errors.push(e.message));await page.goto("http://127.0.0.1:8766/",{waitUntil:"networkidle"});await page.click('[data-tab="update"]');await page.waitForSelector(".update-job-card");
const structure=await page.evaluate(()=>{const root=document.querySelector('[data-page="update"]'),blocks=[...root.children].filter(x=>x.matches('.panel'));return{blocks:blocks.map(x=>x.id),environment:document.querySelectorAll('.environment-chip').length,environmentTips:document.querySelectorAll('.environment-chip .help-tip').length,cards:document.querySelectorAll('#update-cards .metric-card').length,cardTips:document.querySelectorAll('#update-cards .help-tip').length,headerActions:root.querySelectorAll('.page-head button').length,pageSize:document.querySelector('#update-page-size').value,jobs:document.querySelectorAll('.update-job-card').length,progress:getComputedStyle(document.querySelector('#update-progress-fill')).transform,historyClosed:!document.querySelector('#update-history-details').open,logClosed:!document.querySelector('#update-log-details').open}});if(errors.length||structure.blocks.join(',')!=="update-environment,update-overview,update-queue,update-history-details,update-log-details"||structure.environment!==5||structure.environmentTips!==5||structure.cards!==5||structure.cardTips!==5||structure.headerActions||structure.pageSize!=="5"||structure.jobs>5||!structure.historyClosed||!structure.logClosed)throw new Error(JSON.stringify({errors,structure}));
await page.click('#update-environment summary');if(!await page.locator('#update-environment-chips').isVisible())throw new Error('Ambiente não abriu');await page.click('#update-environment-refresh');await page.click('#update-environment summary');
await page.click('#update-select-page');if(!await page.locator('#update-selected-count').textContent().then(x=>!x.startsWith('0 ')))throw new Error('Seleção da página falhou');await page.click('#update-select-page');if(!await page.locator('#update-selected-count').textContent().then(x=>x.startsWith('0 ')))throw new Error('Desmarcação da página falhou');await page.click('#update-select-all');if(await page.locator('#update-selected-count').textContent()==='0 selecionados')throw new Error('Seleção global falhou');await page.click('#update-clear-selection');
const first=page.locator('[data-update-select]').first();await first.click();await page.waitForSelector('#update-detail-modal[open]');await page.keyboard.press('Escape');await page.click('#update-history-details summary');if(!await page.locator('#update-history').isVisible())throw new Error('Histórico não abriu');await page.click('#update-log-details summary');if(!await page.locator('#update-log').isVisible())throw new Error('Log não abriu');
const pages=+await page.locator('#update-pages').textContent();if(pages>1){await page.fill('#update-page-input','2');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('#update-page-input').value==='2')}
for(const [tab,selector] of Object.entries({compare:'#comparison-page-size',add:'#add-page-size',store:'#store-page-size'})){if(await page.locator(selector).inputValue()!=="5")throw new Error(`${tab} não inicia com 5 itens`)}
await page.setViewportSize({width:375,height:800});await page.click('[data-tab="update"]');const mobile=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,columns:getComputedStyle(document.querySelector('.update-filter-grid')).gridTemplateColumns.split(' ').length}));if(mobile.overflow||mobile.columns!==1)throw new Error(JSON.stringify(mobile));if(errors.length)throw new Error(JSON.stringify(errors));console.log(JSON.stringify({ok:true,blocks:5,environment:true,overview:true,queue:true,history:true,logs:true,defaultPageSize:5,detailsModal:true,selection:true,pagination:true,consoleErrors:0}));}finally{await browser.close()}
